security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            remember_me:
                secret:   '%secret%'
                lifetime: 31536000
                path:     /
            pattern: ^/
            form_login:
                provider: fos_userbundle
                require_previous_session: false
                success_handler: app.security.authentication_handler
                failure_handler:  app.security.authentication_handler
                #csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/permutation, role: ROLE_USER }
        - { path: ^/permutation_classes, role: ROLE_USER }
        - { path: ^/covoiturage, role: ROLE_USER }
        - { path: ^/colocations, role: ROLE_USER }