colocations_new:
    path:     /new
    defaults: { _controller: "AppBundle:Colocation:new" }
    methods:  [GET, POST]
    
colocations_delete:
    path: /delete/{id}
    defaults:   {   _controller:    "AppBundle:Colocation:delete"  }

colocation_upload_pictures:
    path:   /upload_colpics
    defaults:   {   _controller:    "AppBundle:Colocation:uploadPictures"  }

colocations_add:
    path:     /add
    defaults: { _controller: "AppBundle:Colocation:add" }
    methods:  [GET, POST]

colocations_index:
    path:   /
    defaults:   {   _controller:    "AppBundle:Colocation:index"  }

colocations_single:
    path: /details/{id}
    defaults:   {   _controller:    "AppBundle:Colocation:single"  }

colocations_disable:
    path: /disable/{id}
    defaults:   {   _controller:    "AppBundle:Colocation:disable"  }

colocations_enable:
    path: /enable/{id}
    defaults:   {   _controller:    "AppBundle:Colocation:enable"  }