covoiturage_index:
    path:     /
    defaults: { _controller: "AppBundle:Covoiturage:index" }
    methods:  [GET, POST]

covoiturage_new:
    path:     /new
    defaults: { _controller: "AppBundle:Covoiturage:new" }
    methods:  [GET, POST]

covoiturage_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Covoiturage:delete" }
    methods:  [GET,DELETE]
