AppBundle\Entity\Permutation:
    type: entity
    table: Permutation
    repositoryClass: AppBundle\Repository\PermutationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        user:
            type: integer
        target:
            type: string
            length: 255
        date:
            type: date
        state:
            type: integer
    lifecycleCallbacks: {  }
